# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Github actions cicd

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: ["main"]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: checkout main branch from GitHub
      uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Have GitHub Actions Build Maven Project
      run: |
        mvn -B package --file pom.xml
        mkdir staging && cp target/*.jar staging
    - name: Set up a cache for Maven
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Persist workflow data as artifacts
      uses: actions/upload-artifact@v3
      with:
       name: github-actions-artifact
       path: staging
  deploy:
    needs: build
    name: deploy
    runs-on: windows-latest
    steps:
      - name: Download JAR
        uses: actions/download-artifact@v3
        with:
          name: github-actions-artifact
      # deploy the artifact (JAR) into AWS Beanstalk
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          use_existing_version_if_available: true
          application_name:  github-cicd-actions
          environment_name: Githubcicdactions-env
          version_label: ${{ github.SHA }}
          region: us-east-1
          deployment_package: githubactions-cicd-0.0.1-SNAPSHOT.jar
